services:
  spring:
    image: 'springboot/boilerplate:0.0.1'
    build:
      context: '.'
    ports:
      - '8081:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=local'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'  # Postgres에 연결
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'TZ=Asia/Seoul'
    depends_on:
      - postgres
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'TZ=Asia/Seoul'
    ports:
      - '5430:5432'
